#서버설정
server:
  port: 8089
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      
#뷰리졸버
spring:
  mvc:
    view:
      prefix: /WEB-INF/jblog/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/duru
    username: root
    password: 1234

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate.format_sql: true